spring.application.name=securevotebackend
server.port=8080

# H2 Database
spring.datasource.url=jdbc:mysql://localhost:3306/securevote?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate for MySQL (updated dialect for Hibernate 6.x)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AI API URL
ai.api.url=http://localhost:5000

# Blockchain
blockchain.ethereum.rpc-url=${ETHEREUM_RPC_URL:http://localhost:7545}
blockchain.ethereum.contract-address=${VOTING_CONTRACT_ADDRESS:0x73CeBCb7BcF54858b0589950bd0734Ba4468ef33}
blockchain.ethereum.private-key=${PRIVATE_KEY:0xbfdc2445c90f00bdbd59871895d734e414686a88f79f7ea136e32a7b7d197227}

logging.level.org.springframework.security=DEBUG
logging.level.com.securevote.securevotebackend=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false


spring.jpa.open-in-view=false
